### ISSUE TITLE
spotify doesn't start up

### ISSUE THREAD

**Issue by awesomec26** [Lyceris-chan/Spotify-adblock#2]
when I ran the batch file, spotify doesn't even start up anymore

**Comment by Lyceris-chan** [comment]
what version of spotify are you using and did you download the latest version of the script?

**Comment by awesomec26** [comment]
i resolved the issue by changing the version of spotify 5 minutes after i originally posted this comment. I forgot this comment existed lol. Sorry for wasting your time
